server.compression.enabled: true
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}/${POSTGRES_DB:jimmy}
  jpa:
    properties.hibernate.jdbc.lob.non_contextual_creation: true
management:
  endpoints.web:
    base-path: /api/actuator
    exposure.include:
      - "info"
      - "health"
      - "metrics"
  endpoint:
    health:
      show-details: when_authorized
      roles: "ADMIN"
      cache.time-to-live: 15s
    metrics:
      cache.time-to-live: 15s

keycloak:
  realm: ${KEYCLOAK_REALM:jimmy}
  principal-attribute: preferred_username
  auth-server-url: ${KEYCLOAK_URL}
  resource: ${KEYCLOAK_CLIENT_NAME:jimmy-back}
  public-client: true
  bearer-only: true
  cors: true

---

spring.profiles: prod
server.port: 8080

---

spring.profiles: dev
server.port: 8181
logging.level:
  fr.alecharp: DEBUG
spring:
  datasource:
    username: jimmy
    password: jimmy
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      type: trace
keycloak:
  auth-server-url: http://localhost:8082/auth
