server.compression.enabled: true
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:jimmy}
  jpa:
    properties.hibernate.jdbc.lob.non_contextual_creation: true
    open-in-view: false
management:
  endpoints.web:
    base-path: /api/actuator
    exposure.include:
      - "info"
      - "health"
      - "metrics"
  endpoint:
    health:
      show-details: when_authorized
      roles: "ADMIN"
      cache.time-to-live: 15s
    metrics:
      cache.time-to-live: 15s

keycloak:
  principal-attribute: preferred_username
  bearer-only: true
  ssl-required: "external"
  confidential-port: 0

---

spring.profiles: production
server.port: 8080
spring.datasource:
  username: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
keycloak:
  realm: ${KEYCLOAK_REALM}
  auth-server-url: ${KEYCLOAK_URL}
  resource: ${KEYCLOAK_CLIENT_ID}

logging.level:
  fr.alecharp.jimmy: INFO

---

spring.profiles: development
server.port: 8181
logging.level:
  fr.alecharp.jimmy: DEBUG
spring:
  datasource:
    username: jimmy
    password: jimmy
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      type: trace
keycloak:
  auth-server-url: http://localhost:8082/auth
  realm: jimmy
  resource: jimmy-back
